### ISSUE TITLE
ImageParser returns invalid image

### ISSUE THREAD

**Issue by austenito** [gottfrois/link_thumbnailer#107]
Gem Version: 3.3.0

When running the following:

```
LinkThumbnailer.generate('https://www.lyft.com/app')
```

The following error occurs:

```
NoMethodError: undefined method `type' for nil:NilClass
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/image_parser.rb:18:in `type'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/models/image.rb:15:in `initialize'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:31:in `new'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:31:in `modelize'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:26:in `block in model'
from /Users/computer/.gem/ruby/2.3.1/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
from /Users/computer/.gem/ruby/2.3.1/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
from /Users/computer/.gem/ruby/2.3.1/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `each'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:24:in `map'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:24:in `model'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:20:in `value'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:10:in `value'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/base.rb:27:in `call'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scrapers/opengraph/images.rb:10:in `call'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scraper.rb:37:in `block (2 levels) in call'
from /Users/computer/.gem/ruby/2.3.1/gems/link_thumbnailer-3.3.0/lib/link_thumbnailer/scraper.rb:36:in `each'
```

From digging in a bit, it looks like the initialize block in `LinkThumbnailer#parser` is returning an empty array for the following:

```
@images = perform? ? ::ImageInfo.from(urls, max_concurrency: max_concurrency) : Array(urls).compact.map(&method(:build_default_image))
```

**Comment by gottfrois** [comment]
Doesn't raise anymore with `v3.4.0`:

```ruby
2.6.6 :019 > LinkThumbnailer.generate('https://www.lyft.com/app')
 => #<LinkThumbnailer::Models::Website:0x00007fad0bb73aa8 @images=[], @videos=[], @url=#<URI::HTTPS https://c.singular.net/api/v1/ad?st=385067100869&h=f21797d077790baadaf428a6ed5af12aab71e9f6>, @title="", @description=nil, @favicon="">
```
