### ISSUE TITLE
NoMethodError: undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by alexis** [gottfrois/link_thumbnailer#66]
Hi,

Could you check what's happening with the following?

    LinkThumbnailer.generate('http://yandex.ru')

```
ETHON: started MULTI
ETHON: performed MULTI
NoMethodError: undefined method `size' for nil:NilClass
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/image_parser.rb:13:in `size'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/models/image.rb:14:in `initialize'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/image.rb:27:in `new'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/image.rb:27:in `modelize'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/image.rb:23:in `block in model'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/image.rb:23:in `map'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/image.rb:23:in `model'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/image.rb:19:in `value'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/image.rb:9:in `value'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/base.rb:27:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/opengraph/images.rb:10:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scraper.rb:37:in `block (2 levels) in call'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scraper.rb:36:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scraper.rb:36:in `block in call'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scraper.rb:35:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scraper.rb:35:in `call'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/page.rb:18:in `generate'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer.rb:16:in `generate'
        from (irb):36
```

**Comment by gottfrois** [comment]
I will have a look thx

**Comment by gottfrois** [comment]
It was an issue on [ImageInfo](https://github.com/gottfrois/image_info) gem. Running `bundle update link_thumbnailer` should fix the issue.
