### ISSUE TITLE
URI::BadURIError: both URI are relative

### ISSUE THREAD

**Issue by maia** [gottfrois/link_thumbnailer#68]
I've come across a rare URI::BadURIError error, details see here: 
````
> LinkThumbnailer.generate("http://www.cashstudios.co/last-photo-project")
URI::BadURIError: both URI are relative
	from …/rubies/ruby-2.2.2/lib/ruby/2.2.0/uri/generic.rb:1100:in `rescue in merge'
	from …/rubies/ruby-2.2.2/lib/ruby/2.2.0/uri/generic.rb:1097:in `merge'
	from …/rubies/ruby-2.2.2/lib/ruby/2.2.0/uri/rfc3986_parser.rb:88:in `each'
	from …/rubies/ruby-2.2.2/lib/ruby/2.2.0/uri/rfc3986_parser.rb:88:in `inject'
	from …/rubies/ruby-2.2.2/lib/ruby/2.2.0/uri/rfc3986_parser.rb:88:in `join'
	from …/rubies/ruby-2.2.2/lib/ruby/2.2.0/uri/common.rb:264:in `join'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/default/images.rb:51:in `prefix_uri'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/default/images.rb:35:in `block in abs_urls'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/default/images.rb:30:in `map'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/default/images.rb:30:in `abs_urls'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/default/images.rb:22:in `allowed_urls'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/default/images.rb:18:in `images'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/default/images.rb:10:in `value'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scrapers/base.rb:27:in `call'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scraper.rb:37:in `block (2 levels) in call'
	from …/gems/ruby-2.2.2/gems/link_thumbnailer-3.0.2/lib/link_thumbnailer/scraper.rb:36:in `each'
````

**Comment by mada41** [comment]
same issue :(

**Comment by maia** [comment]
Thanks!
