### ISSUE TITLE
NoMethodError: undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by maia** [gottfrois/link_thumbnailer#70]
On rare occasions a redirected url does not seem to have a response['location'], causing the following:
````
> LinkThumbnailer.generate("http://www.egms.de/de/journals/mbi")
NoMethodError: undefined method `start_with?' for nil:NilClass
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:73:in `resolve_relative_url'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:63:in `perform_request'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:27:in `block in call'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:35:in `with_valid_url'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:24:in `call'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:62:in `perform_request'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:27:in `block in call'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:35:in `with_valid_url'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/processor.rb:24:in `call'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer/page.rb:17:in `generate'
.../link_thumbnailer-3.0.2/lib/link_thumbnailer.rb:16:in `generate'
````

**Comment by maia** [comment]
Thanks!
