### ISSUE TITLE
undefined method `size' for nil:NilClass 

### ISSUE THREAD

**Issue by 6thSigma** [gottfrois/link_thumbnailer#88]
I'm getting `undefined method 'size' for nil:NilClass` on a couple of URLs.

```
a = LinkThumbnailer.generate('https://www.ixl.com/science/grade-2/classify-matter-as-solid-or-liquid')
```
```
ETHON: Libcurl initialized
ETHON: started MULTI
ETHON: performed MULTI
NoMethodError: undefined method `size' for nil:NilClass
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/image_parser.rb:13:in `size'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/models/image.rb:14:in `initialize'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:27:in `new'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:27:in `modelize'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:23:in `block in model'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:23:in `map'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:23:in `model'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:19:in `value'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/image.rb:9:in `value'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/base.rb:27:in `call'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scrapers/opengraph/images.rb:10:in `call'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scraper.rb:37:in `block (2 levels) in call'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/link_thumbnailer-3.2.0/lib/link_thumbnailer/scraper.rb:36:in `each'
... 16 levels...
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/commands/rails.rb:6:in `call'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/command_wrapper.rb:38:in `call'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/application.rb:183:in `block in serve'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/application.rb:156:in `fork'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/application.rb:156:in `serve'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/application.rb:131:in `block in run'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/application.rb:125:in `loop'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/application.rb:125:in `run'
        from /Users/me/.rvm/gems/ruby-2.2.4/gems/spring-1.5.0/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /Users/me/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/me/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Same error happens for `http://playbook.samaltman.com/` too.

**Comment by gottfrois** [comment]
Thanks for reporting, I'll have a closer look and push a fix :)

**Comment by naiyyar** [comment]
I am getting this issue on some URLs. same error logs @6thSigma has mentioned.

**Comment by gottfrois** [comment]
Can you try with master branch? Haven't released a version yet

**Comment by 6thSigma** [comment]
The two URLs I opened the ticket with are now working using the master branch. Thanks @alfie-max and @gottfrois 

I will keep this open in case you want to close it with a release.

**Comment by gottfrois** [comment]
`v3.2.1`
